apiVersion: v1
kind: Secret
metadata:
  name: protoforge-db-secret
type: Opaque
stringData:
  username: protoforge
  password: CHANGE_ME_STRONG_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: protoforge-jwt-secret
type: Opaque
stringData:
  secret: CHANGE_ME_RANDOM_JWT_SECRET
